"""settleflow: open-source UPI/NPCI settlement reconciliation for India."""

from .models import (
    BatchRecon,
    Match,
    MatchStatus,
    OrderMatch,
    OrderReconResult,
    ReconLine,
    ReconResult,
    Settlement,
    Txn,
    normalize_utr,
)
from .matching import group_batches, match, match_orders, match_settlements, normalize_ref
from .parsers import (
    RAZORPAY_RECON_KEYS,
    RAZORPAY_RECON_REQUIRED,
    load_bank_statement_drcr,
    load_bank_statement_text,
    load_csv,
    load_razorpay_recon_json,
    load_recon_csv,
    parse_amount,
    parse_bank_text,
    parse_date,
    parse_drcr_statement,
    parse_razorpay_recon,
    parse_razorpay_settlements,
)
from .exports import (
    TDS_1035_CODE,
    TDS_1035_RATE,
    export_gst_worksheet,
    export_tally_csv,
    export_tds_1035,
)
from .exceptions import Exception, build_llm_prompt, classify, triage_exceptions
from .pdf import (
    PdfEncryptedError,
    PdfLayoutError,
    PdfScannedError,
    extract_pdf_text,
    parse_sbi_credit_card,
    parse_sbi_netbanking,
    parse_sbi_pdf,
    parse_sbi_statement,
)
from .schemas import (
    API_PARSERS,
    BANK_STATEMENT_MAPS,
    RECON_CSV_MAPS,
    SETTLEMENT_CSV_MAPS,
    BankColumnMap,
    ColumnMap,
    ReconColumnMap,
    load_bank_statement,
    load_settlement_csv,
    load_vendor_recon_csv,
)

__version__ = "0.7.0"

__all__ = [
    "BatchRecon",
    "Match",
    "MatchStatus",
    "OrderMatch",
    "OrderReconResult",
    "ReconLine",
    "ReconResult",
    "Settlement",
    "Txn",
    "normalize_utr",
    "normalize_ref",
    "group_batches",
    "match",
    "match_orders",
    "match_settlements",
    "RAZORPAY_RECON_KEYS",
    "RAZORPAY_RECON_REQUIRED",
    "load_csv",
    "load_bank_statement_drcr",
    "load_bank_statement_text",
    "load_razorpay_recon_json",
    "load_recon_csv",
    "parse_amount",
    "parse_bank_text",
    "parse_date",
    "parse_drcr_statement",
    "parse_razorpay_recon",
    "parse_razorpay_settlements",
    "TDS_1035_CODE",
    "TDS_1035_RATE",
    "export_gst_worksheet",
    "export_tally_csv",
    "export_tds_1035",
    "Exception",
    "build_llm_prompt",
    "classify",
    "triage_exceptions",
    "PdfEncryptedError",
    "PdfLayoutError",
    "PdfScannedError",
    "extract_pdf_text",
    "parse_sbi_pdf",
    "parse_sbi_statement",
    "parse_sbi_credit_card",
    "parse_sbi_netbanking",
    "API_PARSERS",
    "BANK_STATEMENT_MAPS",
    "RECON_CSV_MAPS",
    "SETTLEMENT_CSV_MAPS",
    "BankColumnMap",
    "ColumnMap",
    "ReconColumnMap",
    "load_bank_statement",
    "load_settlement_csv",
    "load_vendor_recon_csv",
]
